-- return {
--   {
--     "olimorris/codecompanion.nvim",
--     dependencies = {
--       "nvim-lua/plenary.nvim",
--       "nvim-treesitter/nvim-treesitter",
--       "hrsh7th/nvim-cmp",
--       "nvim-telescope/telescope.nvim",
--       { "stevearc/dressing.nvim", opts = {} }, -- Optional: Improves `vim.ui.select`
--     },
--     config = function()
--       require("codecompanion").setup({
--         adapters = {
--           gemini = function()
--             return require("codecompanion.adapters").extend("gemini", {
--               env = {
--                 api_key = "AIzaSyCraPaTokY8tOt9TiVon-sLx2oylxLt2c8"
--               },
--             })
--           end,
--         },
--         strategies = {
--           chat = {
--             adapter = "gemini",
--           },
--           inline = {
--             adapter = "gemini",
--           },
--           agent = {
--             adapter = "gemini",
--           },
--         },
--         display = {
--           chat = {
--             window = {
--               layout = "vertical", -- float|vertical|horizontal|buffer
--             },
--           },
--         },
--       })
--     end,
--   },
-- }

-- require("codecompanion").setup({
--   strategies = {
--     chat = {
--       adapter = "gemini",
--     },
--     inline = {
--       adapter = "gemini",
--     },
--     agent = {
--       adapter = "gemini",
--     },
--   },
--   adapters = {
--     gemini = function()
--       return require("codecompanion.adapters").extend("gemini", {
--         env = {
--           api_key = "AIzaSyCraPaTokY8tOt9TiVon-sLx2oylxLt2c8"
--         },
--       })
--     end,

-- Expand 'cc' into 'CodeCompanion' in the command line
